(function(){'use strict';
function boot(){
const $=id=>document.getElementById(id), el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n;}, set=(id,text)=>{$(id).textContent=text??'—';};
const severity={Healthy:['证据正常','good'],Attention:['需要关注','warn'],'Action Required':['需要处理','bad']};
const states={COMMAND_READY:'等待执行',CODEX_RUNNING:'执行中',REPORT_READY:'等待复核',FINALIZING:'正在收尾',FINAL_REPORT_READY:'最终报告待复核',HUMAN_REQUIRED:'等待 Owner 决策',RECOVERY_REQUIRED:'等待恢复核对',FAILED:'执行失败',DONE:'已完成'};
const outcomes={SUCCESS:'执行成功',FAILED:'执行失败',BLOCKED:'任务阻塞',NETWORK_INTERRUPTED:'网络中断'};
const errors={'self-maintenance protected-path guard rejected the last run':'上次自维护未通过路径保护检查。失败记录保留，需要修复根因并重新验证。','worker heartbeat is stale or unavailable':'Worker 心跳过期或不可用，当前进程是否存活尚未确认。','launcher heartbeat is stale or unavailable':'Launcher 心跳过期或不可用，需要检查日常启动服务。','worker health evidence unavailable or corrupt':'Worker 健康证据缺失或损坏。','launcher health evidence unavailable or corrupt':'Launcher 健康证据缺失或损坏。','coordinator resource registry unavailable':'资源登记证据不可用，槽位占用待核对。','runtime configuration unavailable':'无法读取本机项目配置，项目清单可能不完整。','worker process liveness unconfirmed':'未确认 Worker 进程存活，不能据此认领新任务。','example configuration in use':'正在读取示例配置，不能作为正式项目清单。'};
const errorText=x=>errors[x]||(String(x).includes('SELF_MAINTENANCE')?'自维护路径保护检查失败。':String(x).startsWith('OWNER_STOP')?'Owner 已停止这次运行；请先检查部分执行产生的影响。':String(x).includes('lease')?'运行租约缺失、过期或身份不一致。':String(x).includes('heartbeat')?'心跳已过期，运行存活未确认。':String(x).includes('canonical')?'项目权威状态证据异常。':String(x).includes('TIMEOUT')||String(x).includes('timeout')?'执行超时，需要检查运行记录。':String(x).includes('recovery')?'存在尚未核对的恢复证据。':String(x).includes('BLOCKED')?'模型返回任务阻塞，需要核对依赖或 Owner 决策。':String(x).includes('PROCESS_EXITED')?'执行进程已退出，未得到有效完成结果。':states[x]||'存在执行异常，请核对关联运行和恢复证据。');
const fmtDuration=seconds=>seconds===null||seconds===undefined?'时长未知':seconds<60?`${Math.floor(seconds)} 秒`:seconds<3600?`${Math.floor(seconds/60)} 分 ${Math.floor(seconds%60)} 秒`:`${Math.floor(seconds/3600)} 小时 ${Math.floor(seconds%3600/60)} 分`;
const date=s=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'时间未知';
let snapshot=null, selected=new URLSearchParams(location.hash.slice(1)).get('p'), filter='all',runData=null,changedUntil=new Map(),lastSuccess=0,fetching=false,busy=false,toastTimer,stopped=new Set();
const isOffline=()=>!window.BRIDGE_STATIC&&(!lastSuccess||Date.now()-lastSuccess>12000);
const cls=p=>isOffline()&&p.active_run?'warn':(severity[p.severity]||severity.Attention)[1];
const badge=(text,color)=>el('span','badge '+color,text);
const dot=color=>el('span','dot '+color);
const label=p=>p.active_run&&(isOffline()||!snapshot.worker.heartbeat?.fresh||p.active_run.process_alive!==true)?'运行存活待确认':p.owner_paused?'已暂停新任务':states[p.canonical_status]||'状态不可用';
const profile=p=>{const a=p.active_run,r=p.recent_result||{};return [(a?a.model:r.effective_cli_model)||'模型未记录',(a?a.reasoning_effort:r.effective_cli_reasoning_effort)||'推理强度未记录'].join(' · ');};
const announce=message=>{clearTimeout(toastTimer);set('toast',message);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,8000);};
function select(id){selected=id;location.hash='p='+encodeURIComponent(id);runData=null;render();loadRun();}
function render(){if(!snapshot)return;const ps=snapshot.projects||[],w=snapshot.worker||{},c=snapshot.coordinator||{},launch=w.launcher||{},off=isOffline();
set('generated',`${window.BRIDGE_STATIC?'离线快照 · ':''}${date(snapshot.generated_at)}`);
set('side-count',ps.length);set('project-count',ps.length);set('nav-count',ps.filter(p=>p.severity!=='Healthy').length);
const overall=severity[snapshot.severity]||severity.Attention;set('overall',off?'连接中断，状态待确认':overall[0]);$('overall').className=off?'warn':overall[1];$('health-symbol').className='health-symbol '+(off?'warn':overall[1]);set('health-symbol',overall[1]==='good'?'◎':'◈');
set('overall-detail',off?'保留最后一次快照，请勿据此判断当前运行。':snapshot.severity==='Healthy'?'心跳与租约证据均在有效范围内。':`${ps.filter(p=>p.severity!=='Healthy').length} 个项目需要关注 · ${(snapshot.warnings||[]).length} 项主机提示`);
for(const [prefix,item] of [['worker',w],['coordinator',c],['launcher',launch]]){const h=item.heartbeat||{},fresh=h.fresh&&!off;set(prefix+'-status',fresh?(severity[item.severity]||severity.Attention)[0]:'待确认');$(prefix+'-status').className='badge '+(fresh?(severity[item.severity]||severity.Attention)[1]:'warn');set(prefix+'-age',h.available?`${off?'最后快照 · ':''}心跳 ${fmtDuration(h.age_seconds)}前`:'暂无心跳证据');}
set('worker-extra',`本轮已运行 ${fmtDuration(w.uptime_seconds)}`);set('coordinator-extra',`记录状态 ${c.lifecycle||'未记录'} · 与 Worker 共用心跳`);set('launcher-extra',launch.heartbeat?.last_seen_at?`最近 ${date(launch.heartbeat.last_seen_at)}`:'等待 Launcher 发布证据');
const active=ps.filter(p=>p.active_run),healthyActive=active.filter(p=>p.active_run.lease_consistent&&p.active_run.process_alive===true&&w.heartbeat?.fresh&&!off);
set('metric-active',off?'—':healthyActive.length);set('metric-active-note',active.length===healthyActive.length?'进程存活 + 有效租约 + 新鲜心跳':`${active.length-healthyActive.length} 次运行存活尚未确认`);
set('metric-slots',`${c.active_run_count??'—'} / ${c.max_parallel_runs??'—'}`);$('slot-track').replaceChildren();for(let i=0;i<Math.min(c.max_parallel_runs||1,32);i++)$('slot-track').append(el('span',i<(c.active_run_count||0)?(w.heartbeat?.fresh&&!off?'filled':'uncertain'):''));
set('metric-waiting',ps.filter(p=>!p.owner_paused&&!p.active_run&&(['COMMAND_READY','REPORT_READY','FINAL_REPORT_READY'].includes(p.canonical_status)||p.waiting)).length);set('metric-attention',ps.filter(p=>p.severity==='Action Required').length);$('metric-attention').className=ps.some(p=>p.severity==='Action Required')?'bad':'';set('metric-paused',ps.filter(p=>p.owner_paused).length);
set('control-mode',window.BRIDGE_STATIC?'离线只读快照':snapshot.controls?.enabled&&!off?'Owner 控制已就绪':'观察模式 · 操作尚未就绪');
$('project-nav').replaceChildren();for(const p of ps){const b=el('button','project-nav'+(selected===p.project_id?' active':''));b.append(dot(cls(p)),el('span','',p.project_id));b.onclick=()=>select(p.project_id);$('project-nav').append(b);}
set('active-count',active.length);$('active-runs').replaceChildren();if(!active.length){const empty=el('div','empty-state');empty.append(el('strong','','当前没有已登记的 Codex 运行'),el('span','',w.heartbeat?.fresh?'Worker 将按现有调度策略接取可执行任务。':'心跳尚未确认；此处为空不能作为 Worker 正常的证据。'));$('active-runs').append(empty);}for(const p of active){const a=p.active_run,b=el('button','run-card'),top=el('div','run-card-top');top.append(el('h3','',p.project_id),badge(label(p),cls(p)));b.append(top,el('div','run-task',p.task?.title||`正在执行指令 #${String(a.command_id).padStart(3,'0')}`),el('div','run-config',profile(p)));const foot=el('div','run-footer');foot.append(el('span','',fmtDuration(a.duration_seconds)),el('span','','查看实时活动 ↗'));b.append(foot);b.onclick=()=>select(p.project_id);$('active-runs').append(b);}
$('project-list').replaceChildren();const filtered=ps.filter(p=>filter==='all'||filter==='paused'&&p.owner_paused||filter==='attention'&&p.severity!=='Healthy');for(const p of filtered){const row=el('button','project-row'+(p.project_id===selected?' selected':'')+((changedUntil.get(p.project_id)||0)>Date.now()?' changed':'')),a=el('div'),name=el('div','project-name');name.append(dot(cls(p)),el('span','',p.project_id));const sub=el('div','project-sub',label(p));sub.append(el('code','',p.canonical_status||'UNAVAILABLE'));a.append(name,sub);const b=el('div');b.append(el('div','row-result '+(p.recent_result?.outcome==='FAILED'?'bad':''),p.active_run?'正在执行指令 #'+p.active_run.command_id:outcomes[p.recent_result?.outcome]||'暂无结果元数据'),el('div','row-profile',profile(p)));const refs=el('div','row-refs',`C${p.latest_command??'—'} / R${p.latest_report??'—'}`);refs.append(el('small','',`generation ${p.generation??'—'}`));row.append(a,b,refs);row.onclick=()=>select(p.project_id);$('project-list').append(row);}if(!filtered.length)$('project-list').append(el('div','empty-state','没有符合筛选条件的项目。'));
$('recent-results').replaceChildren();const recent=ps.filter(p=>p.recent_result?.outcome).sort((a,b)=>(b.recent_result.completed_at||'').localeCompare(a.recent_result.completed_at||''));for(const p of recent.slice(0,6)){const r=p.recent_result,row=el('div','recent-row'),middle=el('div','recent-project',p.project_id);middle.append(el('small','',`报告 #${r.report_id}`));row.append(el('span',r.outcome==='SUCCESS'?'good':r.outcome==='FAILED'?'bad':'warn',outcomes[r.outcome]),middle,el('time','',date(r.completed_at)));$('recent-results').append(row);}if(!recent.length)$('recent-results').append(el('div','empty-state','暂无可读取的报告摘要。'));
renderInspector();}
function renderInspector(){const panel=$('inspector-content');panel.replaceChildren();const ps=snapshot.projects||[],p=ps.find(x=>x.project_id===selected);$('close-detail').hidden=!p;set('inspector-title',p?'项目与运行详情':'需要关注');set('page-crumb',p?p.project_id:'运行概览');if(!p){for(const warning of snapshot.warnings||[]){const issue=el('div','issue'),head=el('div','issue-head');head.append(dot('warn'),el('strong','','主机运行提示'));issue.append(head,el('p','',errorText(warning)));panel.append(issue);}for(const item of ps.filter(p=>p.severity!=='Healthy')){const issue=el('div','issue'),head=el('div','issue-head');head.append(dot(cls(item)),el('strong','',item.project_id));issue.append(head,el('p','',item.last_execution_error?errorText(item.last_execution_error):item.recovery?.length?'有待核对的恢复或报告发布证据。':label(item)));const b=el('button','','查看关联运行 →');b.onclick=()=>select(item.project_id);issue.append(b);panel.append(issue);}if(!panel.children.length)panel.append(el('div','empty-state','当前没有需要处理的异常。'));panel.append(el('div','inspector-note','优先确认心跳和运行租约，再处理失败、恢复与 Owner 决策。暂停项目只阻止新任务，正在运行的任务会继续。'));return;}
panel.append(el('div','detail-name',p.project_id),badge(label(p),cls(p)));const description=p.last_execution_error&&!p.active_run?errorText(p.last_execution_error):p.owner_paused?'项目已暂停新任务。恢复会允许现有调度继续，不会重跑历史指令。':p.canonical_status==='HUMAN_REQUIRED'?'需要核对 Owner action 与相关报告。暂停/恢复不会自动解除 HUMAN_REQUIRED；决策须通过现有 Owner action 与 publication 流程。':p.canonical_status==='RECOVERY_REQUIRED'?'存在执行或发布的不确定性。恢复核对完成前，不要重跑指令。':p.active_run?'以下信息来自这次运行的租约、输出活动及生命周期事件。':'项目将按现有 round-robin 与 admission 规则推进。';panel.append(el('p','detail-intro',p.task?.title||''),el('p','detail-intro',description));const meta=el('div','detail-meta');const a=p.active_run,r=p.recent_result||{},runId=a?.run_id||r.run_id;for(const [name,value] of [['Protocol 状态',p.canonical_status],['指令 / 报告',`C${p.latest_command} / R${p.latest_report}`],['generation',p.generation],['运行 ID',runId||'未记录'],[a?'当前模型':'上次模型',(a?a.model:r.effective_cli_model)||'未记录'],[a?'推理强度':'上次推理强度',(a?a.reasoning_effort:r.effective_cli_reasoning_effort)||'未记录'],...(a?[['持续时间',fmtDuration(a.duration_seconds)],['租约有效至',date(a.lease_expires_at)]]:[])]){const row=el('div','meta-row');row.append(el('span','',name),el('b','',value));meta.append(row);}panel.append(meta);
const actions=el('div','actions'),allowed=snapshot.controls?.enabled&&!isOffline()&&!busy&&!window.BRIDGE_STATIC;if(p.owner_selected){const pause=el('button','button',p.owner_paused?'恢复项目':'暂停项目');pause.disabled=!allowed;pause.onclick=()=>confirmAction(p,p.owner_paused?'resume':'pause');actions.append(pause);}if(a){const stop=el('button','button danger',stopped.has(a.run_id)||runData?.stop_requested?'已请求停止':'停止本次运行');stop.disabled=!allowed||!a.lease_consistent||stopped.has(a.run_id)||runData?.stop_requested;stop.onclick=()=>confirmAction(p,'stop');actions.append(stop);}panel.append(actions);if(!allowed)panel.append(el('div','project-sub',busy?'正在提交 Owner 操作，请稍候。':snapshot.controls?.reason==='read_only'?'当前服务以观察模式启动。':'操作需要新版本 Worker 和新鲜心跳证据。'));
if(p.recovery?.length){panel.append(el('h3','detail-section-title','恢复核对'));for(const recovery of p.recovery)panel.append(el('p','detail-intro',`待核对 · ${recovery.status} · ${recovery.run_id||'运行身份待确认'}`));}
if(runId){panel.append(el('h3','detail-section-title',a?'实时工作情况':'最近运行记录'));if(!runData){panel.append(el('div','activity','正在读取本地执行证据…'));}else{const info=el('div','activity',a?runData.activity:(outcomes[r.outcome]||'运行已结束'));info.append(el('small','',runData.available?`输出活动 ${fmtDuration([runData.stderr?.age_seconds,runData.stdout?.age_seconds].filter(x=>x!==null&&x!==undefined).sort((a,b)=>a-b)[0])}前`:'未找到该 run 的本地运行目录'));if(runData.available)info.append(el('small','',`输出量 ${((runData.stderr?.bytes||0)+(runData.stdout?.bytes||0))/1024>=1?Math.round(((runData.stderr?.bytes||0)+(runData.stdout?.bytes||0))/1024)+' KB':((runData.stderr?.bytes||0)+(runData.stdout?.bytes||0))+' B'} · 仅提取结构化活动`));panel.append(info);const events=el('div','event-list');for(const event of runData.events||[]){const row=el('div','event',event.label+(event.exit_code!==undefined?` · exit ${event.exit_code}`:''));row.append(el('time','',date(event.at)));events.append(row);}if((runData.recent_steps||[]).length){events.append(el('h3','detail-section-title','最近工具活动'));for(const step of runData.recent_steps.slice(-6))events.append(el('div','event',step));}if(!events.children.length)events.append(el('div','project-sub','暂无结构化事件；输出静默并不等于运行停止。'));panel.append(events);}}
panel.append(el('p','inspector-note','浏览器展示执行阶段、生命周期和输出活动。原始提示词、命令参数、日志正文及凭据不会传入页面。'));
}
async function confirmAction(p,action){if(busy)return;const names={pause:'暂停项目',resume:'恢复项目',stop:'停止本次运行'};set('confirm-title',`${names[action]} · ${p.project_id}`);set('confirm-description',action==='pause'?'暂停后不再认领新指令，当前运行继续至结束。此操作会通过现有 CAS 发布 Owner 项目设置。':action==='resume'?'恢复后，项目可以按原有调度规则接取新任务。它不会重跑历史指令，也不会解除尚未完成的恢复核对。':'Worker 将清理这次运行的完整进程树，再通过原有生命周期发布失败结果。已产生的文件修改和外部影响不会自动撤销。');set('confirm-button',names[action]);$('confirm-dialog').showModal();$('confirm-dialog').onclose=async()=>{if($('confirm-dialog').returnValue!=='confirm')return;busy=true;renderInspector();const body={project_id:p.project_id,action};if(action==='stop')Object.assign(body,{run_id:p.active_run.run_id,command_id:p.active_run.command_id,generation:p.generation});else body.revision=snapshot.portfolio_revision;try{const res=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json','X-Bridge-Owner':'1'},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});const value=await res.json();if(!res.ok)throw new Error(value.error);if(action==='stop'){stopped.add(body.run_id);announce('停止请求已登记，等待 Worker 清理进程并发布结果。');}else announce('Owner 项目设置已通过 CAS 发布。');}catch(e){announce(e.name==='TimeoutError'?'操作结果尚未确认，请查看最新状态后再决定是否重试。':'操作未确认：状态可能已变化，或发布暂不可用。已保留原有状态，请刷新核对。');}finally{busy=false;await refresh();}};}
async function loadRun(){if(!snapshot||!selected||window.BRIDGE_STATIC)return;const p=snapshot.projects.find(p=>p.project_id===selected),rid=p?.active_run?.run_id||p?.recent_result?.run_id;if(!rid)return;const id=selected;try{const response=await fetch(`/api/run?project=${encodeURIComponent(id)}&run=${encodeURIComponent(rid)}`,{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error();const data=await response.json();if(id===selected){runData=data;renderInspector();}}catch{if(id===selected){runData={available:false,events:[],activity:'运行证据暂不可用'};renderInspector();}}}
async function refresh(){if(fetching||window.BRIDGE_STATIC)return;fetching=true;try{const response=await fetch('/api/health',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error();const next=await response.json();for(const p of next.projects||[]){const old=snapshot?.projects?.find(x=>x.project_id===p.project_id);if(old&&(old.generation!==p.generation||old.owner_paused!==p.owner_paused))changedUntil.set(p.project_id,Date.now()+9000);}snapshot=next;lastSuccess=Date.now();$('offline-banner').hidden=true;set('connection','实时同步');$('connection-dot').className='dot good';render();await loadRun();}catch{set('connection','连接中断');$('connection-dot').className='dot warn';$('offline-banner').hidden=false;set('offline-banner','本地服务暂不可用。保留最后快照，所有 Owner 操作已停用；连接恢复后将自动更新。');lastSuccess=0;render();}finally{fetching=false;}}
$('refresh').onclick=refresh;$('nav-overview').onclick=()=>{selected=null;location.hash='';filter='all';render();};$('nav-attention').onclick=()=>{selected=null;filter='attention';render();};$('close-detail').onclick=()=>{selected=null;runData=null;render();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});
setInterval(()=>{set('clock',new Date().toLocaleTimeString('zh-CN',{hour12:false}));if(isOffline()&&snapshot){set('connection','快照已过期');$('connection-dot').className='dot warn';set('overall','连接中断，状态待确认');$('overall').className='warn';document.querySelectorAll('.actions button').forEach(b=>b.disabled=true);}},1000);
if(window.BRIDGE_STATIC){snapshot=window.BRIDGE_STATIC;set('connection','离线快照');$('offline-banner').hidden=false;set('offline-banner','这是离线只读快照，不会实时更新。');render();}else{refresh();setInterval(refresh,3000);}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
